### ISSUE TITLE
[Chore] 기초세팅

### ISSUE THREAD

**Issue by s9hn** [SOPT-30th-Joint-Seminar-15/Client-Android#1]
## 💡 Issue

프로젝트 기초세팅 중입미다..

## 📝 todo

- [x] 패키지 구조화
- [x] 폰트 삽입
- [x] 이미지 에셋 삽입
- [x] 칼라 삽입
- [x] BaseActivity 및 Fragment 생성
- [x] 기본 util 생성
- [x] Build Gradle 세팅
- [x] 테마 설정
