### ISSUE TITLE
[Inflate]다이얼로그 기능구현

### ISSUE THREAD

**Issue by s9hn** [SOPT-30th-Joint-Seminar-15/Client-Android#11]
## 💡 Issue

ㅈㄱㄴ

## 📝 todo

- [x] 다이얼로그 유틸파일 생성
- [x] create 뷰에 붙이기
- [x] read 뷰에 붙이기
