### ISSUE TITLE
[Layout] 문의쓰기 layout 추가 수정 

### ISSUE THREAD

**Issue by wlwpfh** [SOPT-30th-Joint-Seminar-15/Client-Android#13]
## 💡 Issue
layout 추가 수정합니다.

## 📝 todo
- [x] button 이미지 수정 
- [x] edittext 이미지 수정
- [x] radiobutton 위치 수정
- [x] 주의사항 수정
