### ISSUE TITLE
[Inflate] 문의쓰기 기능 구현

### ISSUE THREAD

**Issue by wlwpfh** [SOPT-30th-Joint-Seminar-15/Client-Android#16]
## 💡 Issue
문의쓰기 기능 구현

## 📝 todo
- [x] 모든 라디오버튼이 하나만 눌리게 설정하기
- [x] 구매관련문의 안의 버튼을 눌렀을 때 안보이게 설정하기
- [x] 클릭한 상태 + 내용 작성했을 때 dialog띄우기
