### ISSUE TITLE
[Remote] 문의 정보 조회 API 적용

### ISSUE THREAD

**Issue by KkamSonLee** [SOPT-30th-Joint-Seminar-15/Client-Android#22]
## 💡 Issue

- 문의 정보 조회 API를 적용하여 RecyclerView에 보여줄 예정입니다.
## 📝 todo

- [x] interface에 service 함수 생성(API 기술)
- [x] Response, Request Data Class 생성
- [x] response 제대로 받아지는지 확인 이전에 쓰던 Data Class로 맞추기
- [x] RecyclewView에 적용
- [x] Flow를 이용한 실시간 업데이트 반영 or Create 완료시에만 Collect

**Comment by KkamSonLee** [comment]
참 잘했어요
