### ISSUE TITLE
[Remote] 문의 삭제 구현

### ISSUE THREAD

**Issue by KkamSonLee** [SOPT-30th-Joint-Seminar-15/Client-Android#27]
## 💡 Issue

문의 삭제를 구현할 예정입니다.
## 📝 todo

- [x] 삭제 요청 API 적용
- [x] 삭제 완료 확인 response 
- [x] 변경된 리스트 서버에서 재 요청

**Comment by KkamSonLee** [comment]
emit이 되는 기준이 참 애매함,, 내일 다시..
