### ISSUE TITLE
[Feat] 문의내역 뷰 만들기

### ISSUE THREAD

**Issue by KkamSonLee** [SOPT-30th-Joint-Seminar-15/Client-Android#4]
## 💡 Issue

동적인 부분을 제외(division 포함)한 정적인 View 구성을 먼저 할 예정입니다.
## 📝 todo

- [x] text theme 명시
- [x] button theme 명시
- [x] recyclerview item 만들기
- [x] visibility 속성 hide 맞춰두기
- [x] 하단 페이지_tv 위치 지정
