### ISSUE TITLE
[Inflate] 문의내역 로직 삽입

### ISSUE THREAD

**Issue by KkamSonLee** [SOPT-30th-Joint-Seminar-15/Client-Android#5]
## 💡 Issue

문의내역 뷰에 로직들을 삽입 할 예정입니다.
## 📝 todo

- [x] adapter 구현( listadapter) - click func param
- [x] 문의에 대한 ViewModel 생성 ( write에서 문의 썼을 때 obverve )
- [x] 리스트 layout 클릭 이벤트로 visibility 조정
- [x] 리스트 아이템(삭제) 클릭 이벤트 - remove
- [x] 페이지 처리 고민 ( 몇개가 넘어갔을 때 다음 페이지 만들지, 아님 페이지 구현 자체를 안할지 -> 1페이지 보이게만)
- [x] 다이어로그 완성 시 삭제 로직 연결
