### ISSUE TITLE
[Feat] 문의쓰기 레이아웃

### ISSUE THREAD

**Issue by wlwpfh** [SOPT-30th-Joint-Seminar-15/Client-Android#6]
## 💡 Issue
문의쓰기 레이아웃을 설정합니다. 

## 📝 todo
- [x] 상단 레이아웃 설정하기 
- [x] 버튼 설정하기
- [x] 버튼 string 설정하기
- [x] 버튼 state 설정하기
